### ISSUE TITLE
async versions?

### ISSUE THREAD

**Issue by billiegoose** [thejameskyle/fixturez#1]
This library looks great; I'm going to try using it to copy git repository test fixtures for use with my library [karma-git-http-server-middleware](https://npm.im/karma-git-http-server-middleware). My only concern is that the synchronous version of fsextra.copy will be blocking and might cause server requests to timeout. If that happens I might open a PR adding async/await versions.

**Comment by jamiebuilds** [comment]
this library is designed for tests

**Comment by billiegoose** [comment]
I have asynchronous tests. :) But no worries! The sync version seems to be working just fine, so no need at the moment.
